---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

```{r, include=FALSE}
# load instacart data 
library(p8105.datasets)
    data(instacart) 
```

Column {data-width=650}
-----------------------------------------------------------------------

### Each Arisle vs Order Number

```{r}
set.seed(1)
instacart %>% 
    group_by(aisle_id) %>% 
    summarize(number = n()) %>% 
    plot_ly(x = ~ aisle_id, y = ~ number, type = "scatter" ,
mode = "lines", fill = "tozeroy")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Order of Day vs Demand per hour 

```{r}
set.seed(1)
Order_hours =
  instacart %>% 
  mutate(order_hour_of_day = as.numeric(order_hour_of_day)) %>% 
  filter(!is.na(order_id))  %>% 
  sample_n(10000) 
Order_hours %>% 
  group_by(order_dow, order_hour_of_day) %>% 
  summarize(demand_per_hour = n()) %>% 
  plot_ly(x = ~ order_hour_of_day, y = ~demand_per_hour, type = "violin", colors = "Set2" )
```

### Number of Order vs Department 

```{r}
instacart %>% 
  count(department, sort = TRUE) %>% 
  mutate(department = fct_reorder(department, n)) %>% 
  plot_ly(x = ~department, y = ~n, color = ~department,  type = "bar",
          colors = "Set2" )
```

